<?xml version="1.0"?>
<robot name="agribot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Include inertial macros -->
  <xacro:include filename="$(find robot_description)/urdf/inertial_macros.xacro"/>
<xacro:include filename="$(find robot_description)/urdf/skid_steer.urdf.xacro"/>
  <!-- Parameters -->
  <xacro:property name="chassis_length" value="0.7"/>     <!-- meters -->
  <xacro:property name="chassis_width" value="0.5"/>
  <xacro:property name="chassis_height" value="0.3"/>
  <xacro:property name="chassis_mass" value="15.0"/>

  <xacro:property name="wheel_radius" value="0.125"/>
  <xacro:property name="wheel_width" value="0.05"/>
  <xacro:property name="wheel_mass" value="1.0"/>

  <!-- Chassis -->
  <link name="base_link">
    <visual>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
      <material name="grey">
        <color rgba="0.6 0.6 0.6 1.0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
    </collision>
    <xacro:inertial_box mass="${chassis_mass}"
                        x="${chassis_length}" y="${chassis_width}" z="${chassis_height}">
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:inertial_box>
  </link>

  <!-- Top -->
  <link name="top_link">
    <visual>
      <geometry>
        <box size="${chassis_length/4} ${chassis_width} ${chassis_height/2}"/>
      </geometry>
      <material name="grey">
        <color rgba="0.6 0.3 0.6 1.0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="${chassis_length/4} ${chassis_width} ${chassis_height/2}"/>
      </geometry>
    </collision>
    <xacro:inertial_box mass="${chassis_mass/2}"
                        x="${chassis_length/4}" y="${chassis_width}" z="${chassis_height/2}">
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:inertial_box>
  </link>


    <joint name="top_joint" type="fixed">
      <parent link="base_link"/>
      <child link="top_link"/>
      <origin xyz="${chassis_length/4} 0 ${chassis_height/2}" rpy="0 0 0"/>
    </joint>

  <!-- Macro for wheels -->
  <xacro:macro name="wheel" params="prefix x y">
    <link name="${prefix}_wheel">
      <visual>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <material name="black">
          <color rgba="0.1 0.1 0.1 1.0"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </collision>
      <xacro:inertial_cylinder mass="${wheel_mass}"
                               length="${wheel_width}"
                               radius="${wheel_radius}">
        <origin xyz="0 0 0" rpy="0 0 0"/>
      </xacro:inertial_cylinder>
    </link>

    <joint name="${prefix}_joint" type="continuous">
      <parent link="base_link"/>
      <child link="${prefix}_wheel"/>
      <origin xyz="${x} ${y} ${-chassis_height/2}" rpy="0 1.5708 1.5708"/>
      <axis xyz="0 0 1"/>
    </joint>
  </xacro:macro>

  <!-- 4 Wheels: Front Left, Front Right, Rear Left, Rear Right -->
  <xacro:wheel prefix="fl" x="${chassis_length/2 - 0.1}" y="${chassis_width/2 + 0.05}"/>
  <xacro:wheel prefix="fr" x="${chassis_length/2 - 0.1}" y="${-(chassis_width/2 + 0.05)}"/>
  <xacro:wheel prefix="rl" x="${-(chassis_length/2 - 0.1)}" y="${chassis_width/2 + 0.05}"/>
  <xacro:wheel prefix="rr" x="${-(chassis_length/2 - 0.1)}" y="${-(chassis_width/2 + 0.05)}"/>

</robot>
